// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_LAMPBUTTON_H
#define _UI_COMP_LAMPBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT lampButton
#define UI_COMP_LAMPBUTTON_LAMPBUTTON 0
#define UI_COMP_LAMPBUTTON_STATELABEL2 1
#define UI_COMP_LAMPBUTTON_STATEIMAGE2 2
#define UI_COMP_LAMPBUTTON_NAMELABEL2 3
#define _UI_COMP_LAMPBUTTON_NUM 4
lv_obj_t * ui_lampButton_create(lv_obj_t * comp_parent);
void ui_event_comp_lampButton_lampButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
