// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_DateScreen_screen_init(void)
{
    ui_DateScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DateScreen, lv_color_hex(0x161924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureWifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_TemperatureWifget, 100);
    lv_obj_set_height(ui_TemperatureWifget, 100);
    lv_obj_set_x(ui_TemperatureWifget, -75);
    lv_obj_set_y(ui_TemperatureWifget, -60);
    lv_obj_set_align(ui_TemperatureWifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemperatureWifget,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_TemperatureWifget, lv_color_hex(0x465363), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureWifget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperatureWifget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperatureWifget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel = lv_label_create(ui_TemperatureWifget);
    lv_obj_set_width(ui_TemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel, "20°C");
    lv_obj_set_style_text_font(ui_TemperatureLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TemperatureWifget);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "温度");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureArc = lv_arc_create(ui_TemperatureWifget);
    lv_obj_set_width(ui_TemperatureArc, 90);
    lv_obj_set_height(ui_TemperatureArc, 105);
    lv_obj_set_x(ui_TemperatureArc, 0);
    lv_obj_set_y(ui_TemperatureArc, 10);
    lv_obj_set_align(ui_TemperatureArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemperatureArc,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_TemperatureArc, -36, 70);
    lv_arc_set_value(ui_TemperatureArc, 0);
    lv_arc_set_bg_angles(ui_TemperatureArc, 180, 0);

    lv_obj_set_style_bg_color(ui_TemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HumidityWifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_HumidityWifget, 100);
    lv_obj_set_height(ui_HumidityWifget, 100);
    lv_obj_set_x(ui_HumidityWifget, 75);
    lv_obj_set_y(ui_HumidityWifget, -60);
    lv_obj_set_align(ui_HumidityWifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityWifget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumidityWifget, lv_color_hex(0x465363), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityWifget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HumidityWifget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumidityWifget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel = lv_label_create(ui_HumidityWifget);
    lv_obj_set_width(ui_HumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel, "60%");
    lv_obj_set_style_text_font(ui_HumidityLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_HumidityWifget);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "湿度");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityArc = lv_arc_create(ui_HumidityWifget);
    lv_obj_set_width(ui_HumidityArc, 90);
    lv_obj_set_height(ui_HumidityArc, 100);
    lv_obj_set_x(ui_HumidityArc, 0);
    lv_obj_set_y(ui_HumidityArc, 10);
    lv_obj_set_align(ui_HumidityArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_HumidityArc, 50);
    lv_arc_set_bg_angles(ui_HumidityArc, 180, 0);

    lv_obj_set_style_bg_color(ui_HumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MQ2Wifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_MQ2Wifget, 100);
    lv_obj_set_height(ui_MQ2Wifget, 100);
    lv_obj_set_x(ui_MQ2Wifget, -75);
    lv_obj_set_y(ui_MQ2Wifget, 50);
    lv_obj_set_align(ui_MQ2Wifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MQ2Wifget, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_MQ2Wifget, lv_color_hex(0x465363), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MQ2Wifget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MQ2Wifget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MQ2Wifget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQLabel = lv_label_create(ui_MQ2Wifget);
    lv_obj_set_width(ui_MQLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MQLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MQLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQLabel, "20%");
    lv_obj_set_style_text_font(ui_MQLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_MQ2Wifget);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "气体浓度");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQArc = lv_arc_create(ui_MQ2Wifget);
    lv_obj_set_width(ui_MQArc, 90);
    lv_obj_set_height(ui_MQArc, 100);
    lv_obj_set_x(ui_MQArc, 0);
    lv_obj_set_y(ui_MQArc, 10);
    lv_obj_set_align(ui_MQArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MQArc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MQArc, -36, 70);
    lv_arc_set_value(ui_MQArc, 0);
    lv_arc_set_bg_angles(ui_MQArc, 180, 0);

    lv_obj_set_style_bg_color(ui_MQArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MQArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_Panel3, 117);
    lv_obj_set_height(ui_Panel3, 4);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 112);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button12, 80);
    lv_obj_set_height(ui_Button12, 80);
    lv_obj_set_x(ui_Button12, -92);
    lv_obj_set_y(ui_Button12, -63);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_Button12);
    lv_img_set_src(ui_Image14, &ui_img_l2_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, -10);
    lv_obj_set_y(ui_Image14, -12);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image14, 120);
    lv_obj_set_style_shadow_color(ui_Image14, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Image14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 21);
    lv_obj_set_y(ui_Label19, 22);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "ON");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DateScreen, ui_event_DateScreen, LV_EVENT_ALL, NULL);

}
