// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_DateScreen_screen_init(void)
{
    ui_DateScreen = lv_obj_create(NULL);
    lv_obj_add_flag(ui_DateScreen, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_DateScreen, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    ui_object_set_themeable_style_property(ui_DateScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_back);
    ui_object_set_themeable_style_property(ui_DateScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_back);

    ui_TemperatureWifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_TemperatureWifget, 100);
    lv_obj_set_height(ui_TemperatureWifget, 100);
    lv_obj_set_x(ui_TemperatureWifget, -75);
    lv_obj_set_y(ui_TemperatureWifget, -60);
    lv_obj_set_align(ui_TemperatureWifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemperatureWifget,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_TemperatureWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_TemperatureWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_TemperatureWifget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel = lv_label_create(ui_TemperatureWifget);
    lv_obj_set_width(ui_TemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel, "20°C");
    ui_object_set_themeable_style_property(ui_TemperatureLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_TemperatureLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_TemperatureLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TemperatureWifget);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "温度");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureArc = lv_arc_create(ui_TemperatureWifget);
    lv_obj_set_width(ui_TemperatureArc, 90);
    lv_obj_set_height(ui_TemperatureArc, 105);
    lv_obj_set_x(ui_TemperatureArc, 0);
    lv_obj_set_y(ui_TemperatureArc, 10);
    lv_obj_set_align(ui_TemperatureArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemperatureArc,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_TemperatureArc, -36, 70);
    lv_arc_set_value(ui_TemperatureArc, 0);
    lv_arc_set_bg_angles(ui_TemperatureArc, 180, 0);

    lv_obj_set_style_bg_color(ui_TemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HumidityWifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_HumidityWifget, 100);
    lv_obj_set_height(ui_HumidityWifget, 100);
    lv_obj_set_x(ui_HumidityWifget, 80);
    lv_obj_set_y(ui_HumidityWifget, -60);
    lv_obj_set_align(ui_HumidityWifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityWifget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HumidityWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_HumidityWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_HumidityWifget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel = lv_label_create(ui_HumidityWifget);
    lv_obj_set_width(ui_HumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel, "60%");
    ui_object_set_themeable_style_property(ui_HumidityLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_HumidityLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_HumidityLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_HumidityWifget);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "湿度");
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityArc = lv_arc_create(ui_HumidityWifget);
    lv_obj_set_width(ui_HumidityArc, 90);
    lv_obj_set_height(ui_HumidityArc, 100);
    lv_obj_set_x(ui_HumidityArc, 0);
    lv_obj_set_y(ui_HumidityArc, 10);
    lv_obj_set_align(ui_HumidityArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_HumidityArc, 50);
    lv_arc_set_bg_angles(ui_HumidityArc, 180, 0);

    lv_obj_set_style_bg_color(ui_HumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MQ2Wifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_MQ2Wifget, 100);
    lv_obj_set_height(ui_MQ2Wifget, 100);
    lv_obj_set_x(ui_MQ2Wifget, -75);
    lv_obj_set_y(ui_MQ2Wifget, 50);
    lv_obj_set_align(ui_MQ2Wifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MQ2Wifget, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_MQ2Wifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_MQ2Wifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_MQ2Wifget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQLabel = lv_label_create(ui_MQ2Wifget);
    lv_obj_set_width(ui_MQLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MQLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MQLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQLabel, "20°C");
    ui_object_set_themeable_style_property(ui_MQLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_MQLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_MQLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_MQ2Wifget);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "气体浓度");
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQArc = lv_arc_create(ui_MQ2Wifget);
    lv_obj_set_width(ui_MQArc, 90);
    lv_obj_set_height(ui_MQArc, 100);
    lv_obj_set_x(ui_MQArc, 0);
    lv_obj_set_y(ui_MQArc, 10);
    lv_obj_set_align(ui_MQArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MQArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MQArc, 0, 120);
    lv_arc_set_value(ui_MQArc, 20);
    lv_arc_set_bg_angles(ui_MQArc, 180, 0);

    lv_obj_set_style_bg_color(ui_MQArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MQArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_priWifget2 = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_priWifget2, 100);
    lv_obj_set_height(ui_priWifget2, 100);
    lv_obj_set_x(ui_priWifget2, 80);
    lv_obj_set_y(ui_priWifget2, 50);
    lv_obj_set_align(ui_priWifget2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_priWifget2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_priWifget2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_priWifget2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_priWifget2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_priWifget2);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 3);
    lv_obj_set_y(ui_Label39, 25);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "人体检测");
    ui_object_set_themeable_style_property(ui_Label39, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label39, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_priImage = lv_img_create(ui_priWifget2);
    lv_img_set_src(ui_priImage, &ui_img_h2_png);
    lv_obj_set_width(ui_priImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_priImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_priImage, -1);
    lv_obj_set_y(ui_priImage, -12);
    lv_obj_set_align(ui_priImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_priImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_priImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_priImage, 100);

    ui_voiceWifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_voiceWifget, 100);
    lv_obj_set_height(ui_voiceWifget, 100);
    lv_obj_set_x(ui_voiceWifget, 235);
    lv_obj_set_y(ui_voiceWifget, -60);
    lv_obj_set_align(ui_voiceWifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_voiceWifget, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_voiceWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_voiceWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_voiceWifget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_voiceWifget);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 3);
    lv_obj_set_y(ui_Label40, 25);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "声音检测");
    ui_object_set_themeable_style_property(ui_Label40, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label40, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voiceImage = lv_img_create(ui_voiceWifget);
    lv_img_set_src(ui_voiceImage, &ui_img_hh2_png);
    lv_obj_set_width(ui_voiceImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voiceImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voiceImage, -1);
    lv_obj_set_y(ui_voiceImage, -12);
    lv_obj_set_align(ui_voiceImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_voiceImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_voiceImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_voiceImage, 100);

    ui_Panel1 = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 265);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rainWifget = lv_obj_create(ui_DateScreen);
    lv_obj_set_width(ui_rainWifget, 100);
    lv_obj_set_height(ui_rainWifget, 100);
    lv_obj_set_x(ui_rainWifget, 235);
    lv_obj_set_y(ui_rainWifget, 50);
    lv_obj_set_align(ui_rainWifget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rainWifget, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_rainWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_rainWifget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_rainWifget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_rainWifget);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 3);
    lv_obj_set_y(ui_Label41, 25);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "雨滴检测");
    ui_object_set_themeable_style_property(ui_Label41, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label41, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rainImage = lv_img_create(ui_rainWifget);
    lv_img_set_src(ui_rainImage, &ui_img_dd2_png);
    lv_obj_set_width(ui_rainImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rainImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rainImage, -1);
    lv_obj_set_y(ui_rainImage, -12);
    lv_obj_set_align(ui_rainImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rainImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rainImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_rainImage, 100);

    lv_obj_add_event_cb(ui_TemperatureArc, ui_event_TemperatureArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumidityArc, ui_event_HumidityArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MQArc, ui_event_MQArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_priImage, ui_event_priImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_voiceImage, ui_event_voiceImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rainImage, ui_event_rainImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DateScreen, ui_event_DateScreen, LV_EVENT_ALL, NULL);

}
