// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_lampScreen_screen_init(void)
{
    ui_lampScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_lampScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_lampScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_back);
    ui_object_set_themeable_style_property(ui_lampScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_back);
    lv_obj_set_style_text_color(ui_lampScreen, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lampScreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TabView2 = lv_tabview_create(ui_lampScreen, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView2, 319);
    lv_obj_set_height(ui_TabView2, 237);
    lv_obj_set_x(ui_TabView2, -1);
    lv_obj_set_y(ui_TabView2, -14);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "switch");

    ui_lampButton3 = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_lampButton3, 80);
    lv_obj_set_height(ui_lampButton3, 80);
    lv_obj_set_x(ui_lampButton3, -70);
    lv_obj_set_y(ui_lampButton3, -40);
    lv_obj_set_align(ui_lampButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lampButton3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lampButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_lampButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_lampButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_bg_color(ui_lampButton3, lv_color_hex(0xAB79F7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lampButton3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_lampButton3, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_lampButton3, 150, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_lampButton3, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_lampButton3, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_lampButton3, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lampButton3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_lampButton3, lv_color_hex(0xA94949), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lampButton3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_stateLabel1 = lv_label_create(ui_lampButton3);
    lv_obj_set_width(ui_stateLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateLabel1, 17);
    lv_obj_set_y(ui_stateLabel1, 21);
    lv_obj_set_align(ui_stateLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stateLabel1, "OFF");
    lv_obj_clear_flag(ui_stateLabel1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_stateLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_stateLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_stateLabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stateImage1 = lv_img_create(ui_lampButton3);
    lv_img_set_src(ui_stateImage1, &ui_img_l1_png);
    lv_obj_set_width(ui_stateImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateImage1, -11);
    lv_obj_set_y(ui_stateImage1, -12);
    lv_obj_set_align(ui_stateImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stateImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stateImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_stateImage1, 120);

    ui_nameLabel1 = lv_label_create(ui_lampButton3);
    lv_obj_set_width(ui_nameLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nameLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nameLabel1, -19);
    lv_obj_set_y(ui_nameLabel1, 22);
    lv_obj_set_align(ui_nameLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nameLabel1, "灯1");
    ui_object_set_themeable_style_property(ui_nameLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_nameLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_nameLabel1, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lampButton2 = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_lampButton2, 80);
    lv_obj_set_height(ui_lampButton2, 80);
    lv_obj_set_x(ui_lampButton2, 60);
    lv_obj_set_y(ui_lampButton2, -40);
    lv_obj_set_align(ui_lampButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lampButton2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lampButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_lampButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_lampButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_bg_color(ui_lampButton2, lv_color_hex(0xAB79F7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lampButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_lampButton2, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_lampButton2, 150, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_lampButton2, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_lampButton2, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_lampButton2, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lampButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_lampButton2, lv_color_hex(0xA94949), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_lampButton2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_stateLabel3 = lv_label_create(ui_lampButton2);
    lv_obj_set_width(ui_stateLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateLabel3, 17);
    lv_obj_set_y(ui_stateLabel3, 21);
    lv_obj_set_align(ui_stateLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stateLabel3, "OFF");
    lv_obj_clear_flag(ui_stateLabel3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_stateLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_stateLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_stateLabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stateImage3 = lv_img_create(ui_lampButton2);
    lv_img_set_src(ui_stateImage3, &ui_img_l1_png);
    lv_obj_set_width(ui_stateImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateImage3, -11);
    lv_obj_set_y(ui_stateImage3, -12);
    lv_obj_set_align(ui_stateImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stateImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stateImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_stateImage3, 120);

    ui_nameLabel3 = lv_label_create(ui_lampButton2);
    lv_obj_set_width(ui_nameLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nameLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nameLabel3, -19);
    lv_obj_set_y(ui_nameLabel3, 22);
    lv_obj_set_align(ui_nameLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nameLabel3, "灯2");
    ui_object_set_themeable_style_property(ui_nameLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_nameLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_nameLabel3, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "switch1");

    ui_Panel7 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel7, 115);
    lv_obj_set_height(ui_Panel7, 80);
    lv_obj_set_x(ui_Panel7, -76);
    lv_obj_set_y(ui_Panel7, -43);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_Image1, &ui_img_vv1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -30);
    lv_obj_set_y(ui_Image1, -20);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 100);

    ui_Label18 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -30);
    lv_obj_set_y(ui_Label18, 20);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "感应");
    ui_object_set_themeable_style_property(ui_Label18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel7);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 27);
    lv_obj_set_y(ui_Switch1, -16);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States


    ui_Panel12 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel12, 115);
    lv_obj_set_height(ui_Panel12, 80);
    lv_obj_set_x(ui_Panel12, 75);
    lv_obj_set_y(ui_Panel12, -43);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_Panel12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image15, &ui_img_vv1_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, -30);
    lv_obj_set_y(ui_Image15, -20);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image15, 100);

    ui_Label38 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -30);
    lv_obj_set_y(ui_Label38, 20);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "声控");
    ui_object_set_themeable_style_property(ui_Label38, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label38, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Panel12);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 27);
    lv_obj_set_y(ui_Switch3, -16);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch3, LV_STATE_CHECKED);       /// States


    lv_obj_add_event_cb(ui_lampButton3, ui_event_lampButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lampButton2, ui_event_lampButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabView2, ui_event_TabView2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lampScreen, ui_event_lampScreen, LV_EVENT_ALL, NULL);

}
