// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_lampScreen_screen_init(void)
{
    ui_lampScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_lampScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lampScreen, lv_color_hex(0x161924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lampScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lampScreen, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lampScreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TabView2 = lv_tabview_create(ui_lampScreen, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView2, 319);
    lv_obj_set_height(ui_TabView2, 237);
    lv_obj_set_x(ui_TabView2, -1);
    lv_obj_set_y(ui_TabView2, -14);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "switch");

    ui_lampButton1 = ui_lampButton_create(ui_TabPage1);
    lv_obj_set_x(ui_lampButton1, -70);
    lv_obj_set_y(ui_lampButton1, -40);



    ui_lampButton2 = ui_lampButton_create(ui_TabPage1);
    lv_obj_set_x(ui_lampButton2, 50);
    lv_obj_set_y(ui_lampButton2, -40);


    lv_label_set_text(ui_comp_get_child(ui_lampButton2, UI_COMP_LAMPBUTTON_NAMELABEL2), "灯2");

    ui_lampButton3 = ui_lampButton_create(ui_TabPage1);
    lv_obj_set_x(ui_lampButton3, -70);
    lv_obj_set_y(ui_lampButton3, 60);


    lv_label_set_text(ui_comp_get_child(ui_lampButton3, UI_COMP_LAMPBUTTON_NAMELABEL2), "灯3");

    ui_lampButton4 = ui_lampButton_create(ui_TabPage1);
    lv_obj_set_x(ui_lampButton4, 50);
    lv_obj_set_y(ui_lampButton4, 60);


    lv_label_set_text(ui_comp_get_child(ui_lampButton4, UI_COMP_LAMPBUTTON_NAMELABEL2), "灯4");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "color");

    lv_obj_set_style_bg_color(ui_TabPage2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Colorwheel1 = lv_colorwheel_create(ui_TabPage2, true);
    lv_obj_set_width(ui_Colorwheel1, 170);
    lv_obj_set_height(ui_Colorwheel1, 169);
    lv_obj_set_x(ui_Colorwheel1, 8);
    lv_obj_set_y(ui_Colorwheel1, 0);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_Colorwheel1, 20, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel10 = lv_obj_create(ui_lampScreen);
    lv_obj_set_width(ui_Panel10, 117);
    lv_obj_set_height(ui_Panel10, 4);
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, 112);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TabView2, ui_event_TabView2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel10, ui_event_Panel10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lampScreen, ui_event_lampScreen, LV_EVENT_ALL, NULL);

}
