// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_add_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_back);
    ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_back);

    ui_Image2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Image2, &ui_img_icon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image2, -134);
    lv_obj_set_y(ui_Image2, -98);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 80);

    ui_Label2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -80);
    lv_obj_set_y(ui_Label2, -97);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "智能家居");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_smartsystem, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_timeLabel, 125);
    lv_obj_set_y(ui_timeLabel, -99);
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "12:12");
    lv_obj_add_flag(ui_timeLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_timeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_timeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathericonImage = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_weathericonImage, &ui_img_31831977);
    lv_obj_set_width(ui_weathericonImage, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_weathericonImage, LV_SIZE_CONTENT);    /// 85
    lv_obj_set_x(ui_weathericonImage, 77);
    lv_obj_set_y(ui_weathericonImage, -101);
    lv_obj_set_align(ui_weathericonImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathericonImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathericonImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_weathericonImage, 150);

    ui_weathericonImage2 = lv_img_create(ui_weathericonImage);
    lv_img_set_src(ui_weathericonImage2, &ui_img_1282432712);
    lv_obj_set_width(ui_weathericonImage2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_weathericonImage2, LV_SIZE_CONTENT);    /// 85
    lv_obj_set_x(ui_weathericonImage2, -175);
    lv_obj_set_y(ui_weathericonImage2, -12);
    lv_obj_set_align(ui_weathericonImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathericonImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathericonImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_weathericonImage2, 150);

    ui_weathericonImage3 = lv_img_create(ui_weathericonImage);
    lv_img_set_src(ui_weathericonImage3, &ui_img_520433372);
    lv_obj_set_width(ui_weathericonImage3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_weathericonImage3, LV_SIZE_CONTENT);    /// 85
    lv_obj_set_x(ui_weathericonImage3, 38);
    lv_obj_set_y(ui_weathericonImage3, -99);
    lv_obj_set_align(ui_weathericonImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathericonImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathericonImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_weathericonImage3, 150);

    ui_weathericonImage4 = lv_img_create(ui_weathericonImage);
    lv_img_set_src(ui_weathericonImage4, &ui_img_1809401540);
    lv_obj_set_width(ui_weathericonImage4, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_weathericonImage4, LV_SIZE_CONTENT);    /// 85
    lv_obj_set_x(ui_weathericonImage4, 38);
    lv_obj_set_y(ui_weathericonImage4, -99);
    lv_obj_set_align(ui_weathericonImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathericonImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathericonImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_weathericonImage4, 150);

    ui_weatherLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_weatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherLabel, 85);
    lv_obj_set_y(ui_weatherLabel, -72);
    lv_obj_set_align(ui_weatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherLabel, "多云  室外温度:25°C");
    ui_object_set_themeable_style_property(ui_weatherLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_weatherLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_weatherLabel, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 320);
    lv_obj_set_height(ui_Container1, 174);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 30);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container1, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags

    ui_Button6 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button6, 130);
    lv_obj_set_height(ui_Button6, 73);
    lv_obj_set_x(ui_Button6, 230);
    lv_obj_set_y(ui_Button6, -45);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x465363), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Button6);
    lv_img_set_src(ui_Image8, &ui_img_configure_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -32);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 120);

    ui_Label8 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 30);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "配置");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button5, 130);
    lv_obj_set_height(ui_Button5, 73);
    lv_obj_set_x(ui_Button5, 75);
    lv_obj_set_y(ui_Button5, -45);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_Button5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);

    ui_Image7 = lv_img_create(ui_Button5);
    lv_img_set_src(ui_Image7, &ui_img_lamps_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -35);
    lv_obj_set_y(ui_Image7, 0);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 120);

    ui_Label11 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 30);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "LED灯");
    ui_object_set_themeable_style_property(ui_Label11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button3, 130);
    lv_obj_set_height(ui_Button3, 73);
    lv_obj_set_x(ui_Button3, -75);
    lv_obj_set_y(ui_Button3, 40);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_Button3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);

    ui_Image3 = lv_img_create(ui_Button3);
    lv_img_set_src(ui_Image3, &ui_img_s1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -31);
    lv_obj_set_y(ui_Image3, -1);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 110);

    ui_Label5 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 30);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "监控");
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button2, 130);
    lv_obj_set_height(ui_Button2, 73);
    lv_obj_set_x(ui_Button2, -75);
    lv_obj_set_y(ui_Button2, -45);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);

    ui_Image4 = lv_img_create(ui_Button2);
    lv_img_set_src(ui_Image4, &ui_img_data_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -33);
    lv_obj_set_y(ui_Image4, -3);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 120);

    ui_Label6 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 30);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "传感器");
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button4, 130);
    lv_obj_set_height(ui_Button4, 73);
    lv_obj_set_x(ui_Button4, 75);
    lv_obj_set_y(ui_Button4, 40);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_Button4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);

    ui_Image6 = lv_img_create(ui_Button4);
    lv_img_set_src(ui_Image6, &ui_img_chat_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -27);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 100);

    ui_Label29 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 30);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "语音");
    ui_object_set_themeable_style_property(ui_Label29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 263);
    lv_obj_set_y(ui_Panel2, 21);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_cityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cityLabel, 35);
    lv_obj_set_y(ui_cityLabel, -99);
    lv_obj_set_align(ui_cityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cityLabel, "广州");
    ui_object_set_themeable_style_property(ui_cityLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_cityLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_cityLabel, &ui_font_UniversalFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusbarLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_statusbarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusbarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusbarLabel, -27);
    lv_obj_set_y(ui_statusbarLabel, -99);
    lv_obj_set_align(ui_statusbarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusbarLabel, "");
    lv_obj_set_style_text_color(ui_statusbarLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusbarLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_timeLabel, ui_event_timeLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
