// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_monitorScreen_screen_init(void)
{
    ui_monitorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_monitorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_monitorScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_back);
    ui_object_set_themeable_style_property(ui_monitorScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_back);

    ui_Panel4 = lv_obj_create(ui_monitorScreen);
    lv_obj_set_width(ui_Panel4, 117);
    lv_obj_set_height(ui_Panel4, 4);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 112);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectCameraButton = lv_btn_create(ui_monitorScreen);
    lv_obj_set_width(ui_connectCameraButton, 75);
    lv_obj_set_height(ui_connectCameraButton, 32);
    lv_obj_set_x(ui_connectCameraButton, 112);
    lv_obj_set_y(ui_connectCameraButton, -93);
    lv_obj_set_align(ui_connectCameraButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectCameraButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectCameraButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cameraLabel = lv_label_create(ui_connectCameraButton);
    lv_obj_set_width(ui_cameraLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cameraLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cameraLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cameraLabel, "连接");
    lv_obj_set_style_text_font(ui_cameraLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cameraStateLabel = lv_label_create(ui_monitorScreen);
    lv_obj_set_width(ui_cameraStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cameraStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cameraStateLabel, -114);
    lv_obj_set_y(ui_cameraStateLabel, -93);
    lv_obj_set_align(ui_cameraStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cameraStateLabel, "未连接");
    ui_object_set_themeable_style_property(ui_cameraStateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_cameraStateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_cameraStateLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connectCameraButton, ui_event_connectCameraButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_monitorScreen, ui_event_monitorScreen, LV_EVENT_ALL, NULL);

}
