// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_set1Screen_screen_init(void)
{
    ui_set1Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_set1Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_set1Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_back);
    ui_object_set_themeable_style_property(ui_set1Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_back);

    ui_chooseTabView = lv_tabview_create(ui_set1Screen, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_chooseTabView, 314);
    lv_obj_set_height(ui_chooseTabView, 242);
    lv_obj_set_x(ui_chooseTabView, 2);
    lv_obj_set_y(ui_chooseTabView, -7);
    lv_obj_set_align(ui_chooseTabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_chooseTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chooseTabView, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chooseTabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_w1 = lv_tabview_add_tab(ui_chooseTabView, "w");

    ui_Label1 = lv_label_create(ui_w1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -108);
    lv_obj_set_y(ui_Label1, -97);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "WIFI");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSwitch = lv_switch_create(ui_w1);
    lv_obj_set_width(ui_wifiSwitch, 73);
    lv_obj_set_height(ui_wifiSwitch, 33);
    lv_obj_set_x(ui_wifiSwitch, -108);
    lv_obj_set_y(ui_wifiSwitch, -62);
    lv_obj_set_align(ui_wifiSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_wifiSwitch, LV_STATE_CHECKED);       /// States


    ui_wifiStateLabel = lv_label_create(ui_w1);
    lv_obj_set_width(ui_wifiStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStateLabel, -31);
    lv_obj_set_y(ui_wifiStateLabel, -95);
    lv_obj_set_align(ui_wifiStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStateLabel, "已连接");
    ui_object_set_themeable_style_property(ui_wifiStateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_wifiStateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_wifiStateLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifilistPanel = lv_obj_create(ui_w1);
    lv_obj_set_width(ui_wifilistPanel, 200);
    lv_obj_set_height(ui_wifilistPanel, 180);
    lv_obj_set_x(ui_wifilistPanel, 40);
    lv_obj_set_y(ui_wifilistPanel, 10);
    lv_obj_set_align(ui_wifilistPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifilistPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_wifilistPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_wifilistPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_color(ui_wifilistPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifilistPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipLabel = lv_label_create(ui_w1);
    lv_obj_set_width(ui_ipLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ipLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipLabel, 49);
    lv_obj_set_y(ui_ipLabel, -96);
    lv_obj_set_align(ui_ipLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipLabel, "IP:");
    ui_object_set_themeable_style_property(ui_ipLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_ipLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);

    ui_w2 = lv_tabview_add_tab(ui_chooseTabView, "m");

    ui_Label16 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -115);
    lv_obj_set_y(ui_Label16, -64);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "服务器");
    ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttStateLabel = lv_label_create(ui_w2);
    lv_obj_set_width(ui_mqttStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mqttStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mqttStateLabel, -32);
    lv_obj_set_y(ui_mqttStateLabel, -64);
    lv_obj_set_align(ui_mqttStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mqttStateLabel, "未连接");
    ui_object_set_themeable_style_property(ui_mqttStateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_mqttStateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_mqttStateLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -1);
    lv_obj_set_y(ui_Label28, -98);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "设备绑定");
    ui_object_set_themeable_style_property(ui_Label28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -116);
    lv_obj_set_y(ui_Label13, -30);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "账    号");
    ui_object_set_themeable_style_property(ui_Label13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -115);
    lv_obj_set_y(ui_Label17, 7);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "密    码");
    ui_object_set_themeable_style_property(ui_Label17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttuseButton = lv_btn_create(ui_w2);
    lv_obj_set_width(ui_mqttuseButton, 46);
    lv_obj_set_height(ui_mqttuseButton, 28);
    lv_obj_set_x(ui_mqttuseButton, 94);
    lv_obj_set_y(ui_mqttuseButton, 46);
    lv_obj_set_align(ui_mqttuseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mqttuseButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mqttuseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mqttuseButton, lv_color_hex(0xDB82F5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_mqttuseButton, 200, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_mqttConnectStateLabel = lv_label_create(ui_mqttuseButton);
    lv_obj_set_width(ui_mqttConnectStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mqttConnectStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mqttConnectStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mqttConnectStateLabel, "绑定");
    lv_obj_set_style_text_color(ui_mqttConnectStateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mqttConnectStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mqttConnectStateLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_w3 = lv_tabview_add_tab(ui_chooseTabView, "t");
    lv_obj_clear_flag(ui_w3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 1);
    lv_obj_set_y(ui_Label21, -97);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "系统设置");
    ui_object_set_themeable_style_property(ui_Label21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -120);
    lv_obj_set_y(ui_Label22, -67);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "开机语音");
    ui_object_set_themeable_style_property(ui_Label22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -120);
    lv_obj_set_y(ui_Label23, -33);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "校时时长");
    ui_object_set_themeable_style_property(ui_Label23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -120);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "天气城市");
    ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeuseButton = lv_btn_create(ui_w3);
    lv_obj_set_width(ui_timeuseButton, 49);
    lv_obj_set_height(ui_timeuseButton, 28);
    lv_obj_set_x(ui_timeuseButton, 128);
    lv_obj_set_y(ui_timeuseButton, -97);
    lv_obj_set_align(ui_timeuseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeuseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timeuseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_timeuseButton);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "应用");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 28);
    lv_obj_set_y(ui_Label31, -67);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "深色主题");
    ui_object_set_themeable_style_property(ui_Label31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_themeSwitch = lv_switch_create(ui_w3);
    lv_obj_set_width(ui_themeSwitch, 50);
    lv_obj_set_height(ui_themeSwitch, 25);
    lv_obj_set_x(ui_themeSwitch, 94);
    lv_obj_set_y(ui_themeSwitch, -67);
    lv_obj_set_align(ui_themeSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_themeSwitch, LV_STATE_CHECKED);       /// States


    ui_Label36 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, -119);
    lv_obj_set_y(ui_Label36, 31);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "屏幕亮度");
    ui_object_set_themeable_style_property(ui_Label36, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label36, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_w3);
    lv_slider_set_range(ui_Slider1, 0, 255);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 170);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 21);
    lv_obj_set_y(ui_Slider1, 33);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_startAudioSwitch = lv_switch_create(ui_w3);
    lv_obj_set_width(ui_startAudioSwitch, 50);
    lv_obj_set_height(ui_startAudioSwitch, 25);
    lv_obj_set_x(ui_startAudioSwitch, -47);
    lv_obj_set_y(ui_startAudioSwitch, -67);
    lv_obj_set_align(ui_startAudioSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_startAudioSwitch, LV_STATE_CHECKED);       /// States


    ui_W4 = lv_tabview_add_tab(ui_chooseTabView, "S");

    ui_Label19 = lv_label_create(ui_W4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -5);
    lv_obj_set_y(ui_Label19, -87);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "语音配置");
    ui_object_set_themeable_style_property(ui_Label19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_W4);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -109);
    lv_obj_set_y(ui_Label32, -4);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "发音人");
    ui_object_set_themeable_style_property(ui_Label32, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label32, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speechDropdown = lv_dropdown_create(ui_W4);
    lv_dropdown_set_options(ui_speechDropdown, "xiaomei\nxiaoyu\nxiaoyao\nyaya");
    lv_obj_set_width(ui_speechDropdown, 150);
    lv_obj_set_height(ui_speechDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speechDropdown, 30);
    lv_obj_set_y(ui_speechDropdown, -4);
    lv_obj_set_align(ui_speechDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speechDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_speechDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_speechDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    ui_object_set_themeable_style_property(ui_speechDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_speechDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_speechDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label33 = lv_label_create(ui_W4);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -109);
    lv_obj_set_y(ui_Label33, 53);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "AI模型");
    ui_object_set_themeable_style_property(ui_Label33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aimodeDropdown = lv_dropdown_create(ui_W4);
    lv_dropdown_set_options(ui_aimodeDropdown, "Xunfei");
    lv_obj_set_width(ui_aimodeDropdown, 150);
    lv_obj_set_height(ui_aimodeDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aimodeDropdown, 29);
    lv_obj_set_y(ui_aimodeDropdown, 50);
    lv_obj_set_align(ui_aimodeDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aimodeDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_aimodeDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_aimodeDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    ui_object_set_themeable_style_property(ui_aimodeDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_btn);
    ui_object_set_themeable_style_property(ui_aimodeDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_btn);
    lv_obj_set_style_border_width(ui_aimodeDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_W5 = lv_tabview_add_tab(ui_chooseTabView, "c");

    ui_Label66 = lv_label_create(ui_W5);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, -116);
    lv_obj_set_y(ui_Label66, -45);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "IP:");
    ui_object_set_themeable_style_property(ui_Label66, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label66, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label66, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_W5);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, -126);
    lv_obj_set_y(ui_Label67, 0);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "端口:");
    ui_object_set_themeable_style_property(ui_Label67, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label67, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label67, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cameraButton = lv_btn_create(ui_W5);
    lv_obj_set_width(ui_cameraButton, 46);
    lv_obj_set_height(ui_cameraButton, 28);
    lv_obj_set_x(ui_cameraButton, 103);
    lv_obj_set_y(ui_cameraButton, 46);
    lv_obj_set_align(ui_cameraButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cameraButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cameraButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cameraipLabel = lv_label_create(ui_cameraButton);
    lv_obj_set_width(ui_cameraipLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cameraipLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cameraipLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cameraipLabel, "应用");
    lv_obj_set_style_text_color(ui_cameraipLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cameraipLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cameraipLabel, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_W5);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 1);
    lv_obj_set_y(ui_Label35, -89);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "监控设置");
    ui_object_set_themeable_style_property(ui_Label35, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_Label35, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_D1 = lv_tabview_add_tab(ui_chooseTabView, "d");

    ui_pwLabel = lv_label_create(ui_D1);
    lv_obj_set_width(ui_pwLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pwLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pwLabel, -75);
    lv_obj_set_y(ui_pwLabel, -3);
    lv_obj_set_align(ui_pwLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pwLabel, "检测设备重新配网");
    ui_object_set_themeable_style_property(ui_pwLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_pwLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_pwLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_control11Label = lv_label_create(ui_D1);
    lv_obj_set_width(ui_control11Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_control11Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_control11Label, 0);
    lv_obj_set_y(ui_control11Label, -90);
    lv_obj_set_align(ui_control11Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_control11Label, "检测设备配置");
    ui_object_set_themeable_style_property(ui_control11Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_control11Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_control11Label, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_control1Label7 = lv_label_create(ui_D1);
    lv_obj_set_width(ui_control1Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_control1Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_control1Label7, -110);
    lv_obj_set_y(ui_control1Label7, -47);
    lv_obj_set_align(ui_control1Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_control1Label7, "入侵警报");
    ui_object_set_themeable_style_property(ui_control1Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_font);
    ui_object_set_themeable_style_property(ui_control1Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_font);
    lv_obj_set_style_text_font(ui_control1Label7, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mqttuseButton, ui_event_mqttuseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeuseButton, ui_event_timeuseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_themeSwitch, ui_event_themeSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startAudioSwitch, ui_event_startAudioSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cameraButton, ui_event_cameraButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_set1Screen, ui_event_set1Screen, LV_EVENT_ALL, NULL);

}
