// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_set1Screen_screen_init(void)
{
    ui_set1Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_set1Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_set1Screen, lv_color_hex(0x161924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_set1Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_set1Screen);
    lv_obj_set_width(ui_Panel5, 117);
    lv_obj_set_height(ui_Panel5, 4);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, 112);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chooseTabView = lv_tabview_create(ui_set1Screen, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_chooseTabView, 314);
    lv_obj_set_height(ui_chooseTabView, 242);
    lv_obj_set_x(ui_chooseTabView, 2);
    lv_obj_set_y(ui_chooseTabView, -7);
    lv_obj_set_align(ui_chooseTabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_chooseTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chooseTabView, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chooseTabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_w1 = lv_tabview_add_tab(ui_chooseTabView, "w");

    ui_Label1 = lv_label_create(ui_w1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -108);
    lv_obj_set_y(ui_Label1, -97);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "WIFI");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSwitch = lv_switch_create(ui_w1);
    lv_obj_set_width(ui_wifiSwitch, 73);
    lv_obj_set_height(ui_wifiSwitch, 33);
    lv_obj_set_x(ui_wifiSwitch, -109);
    lv_obj_set_y(ui_wifiSwitch, -62);
    lv_obj_set_align(ui_wifiSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_wifiSwitch, LV_STATE_CHECKED);       /// States


    ui_wifiStateLabel = lv_label_create(ui_w1);
    lv_obj_set_width(ui_wifiStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStateLabel, -31);
    lv_obj_set_y(ui_wifiStateLabel, -95);
    lv_obj_set_align(ui_wifiStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStateLabel, "已连接");
    lv_obj_set_style_text_color(ui_wifiStateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiStateLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifilistPanel = lv_obj_create(ui_w1);
    lv_obj_set_width(ui_wifilistPanel, 200);
    lv_obj_set_height(ui_wifilistPanel, 180);
    lv_obj_set_x(ui_wifilistPanel, 40);
    lv_obj_set_y(ui_wifilistPanel, 10);
    lv_obj_set_align(ui_wifilistPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifilistPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifilistPanel, lv_color_hex(0x465363), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifilistPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifilistPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifilistPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_w2 = lv_tabview_add_tab(ui_chooseTabView, "m");

    ui_Label13 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -118);
    lv_obj_set_y(ui_Label13, -53);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "订阅主题");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -118);
    lv_obj_set_y(ui_Label10, 42);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "天气城市");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttSwitch = lv_switch_create(ui_w2);
    lv_obj_set_width(ui_mqttSwitch, 50);
    lv_obj_set_height(ui_mqttSwitch, 25);
    lv_obj_set_x(ui_mqttSwitch, -4);
    lv_obj_set_y(ui_mqttSwitch, -95);
    lv_obj_set_align(ui_mqttSwitch, LV_ALIGN_CENTER);


    ui_Label16 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -98);
    lv_obj_set_y(ui_Label16, -95);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "MQTT服务器");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_w2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -118);
    lv_obj_set_y(ui_Label17, -3);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "发布主题");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttuseButton = lv_btn_create(ui_w2);
    lv_obj_set_width(ui_mqttuseButton, 46);
    lv_obj_set_height(ui_mqttuseButton, 28);
    lv_obj_set_x(ui_mqttuseButton, 89);
    lv_obj_set_y(ui_mqttuseButton, 74);
    lv_obj_set_align(ui_mqttuseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mqttuseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mqttuseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_mqttuseButton);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "应用");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttStateLabel = lv_label_create(ui_w2);
    lv_obj_set_width(ui_mqttStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mqttStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mqttStateLabel, 63);
    lv_obj_set_y(ui_mqttStateLabel, -93);
    lv_obj_set_align(ui_mqttStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mqttStateLabel, "未连接");
    lv_obj_set_style_text_color(ui_mqttStateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mqttStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mqttStateLabel, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_w3 = lv_tabview_add_tab(ui_chooseTabView, "t");

    ui_Label21 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 1);
    lv_obj_set_y(ui_Label21, -89);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "时间设置");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -118);
    lv_obj_set_y(ui_Label22, -43);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "NTP服务");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_w3);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -118);
    lv_obj_set_y(ui_Label23, 5);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "校时时长");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeuseButton = lv_btn_create(ui_w3);
    lv_obj_set_width(ui_timeuseButton, 46);
    lv_obj_set_height(ui_timeuseButton, 28);
    lv_obj_set_x(ui_timeuseButton, 87);
    lv_obj_set_y(ui_timeuseButton, 62);
    lv_obj_set_align(ui_timeuseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeuseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timeuseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_timeuseButton);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "应用");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_weatherfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mqttuseButton, ui_event_mqttuseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeuseButton, ui_event_timeuseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_set1Screen, ui_event_set1Screen, LV_EVENT_ALL, NULL);

}
