// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_speechScreen_screen_init(void)
{
    ui_speechScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_speechScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_speechScreen, lv_color_hex(0x161924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speechScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_speechScreen);
    lv_obj_set_width(ui_Panel8, 117);
    lv_obj_set_height(ui_Panel8, 4);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, 112);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView4 = lv_tabview_create(ui_speechScreen, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView4, 320);
    lv_obj_set_height(ui_TabView4, 240);
    lv_obj_set_align(ui_TabView4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_s1 = lv_tabview_add_tab(ui_TabView4, "speech");

    ui_s2 = lv_tabview_add_tab(ui_TabView4, "music");

    ui_prevButton = lv_btn_create(ui_s2);
    lv_obj_set_width(ui_prevButton, 50);
    lv_obj_set_height(ui_prevButton, 40);
    lv_obj_set_x(ui_prevButton, -70);
    lv_obj_set_y(ui_prevButton, 40);
    lv_obj_set_align(ui_prevButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_prevButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_prevButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_prevLabel = lv_label_create(ui_prevButton);
    lv_obj_set_width(ui_prevLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_prevLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_prevLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_prevLabel, "");

    ui_nextButton = lv_btn_create(ui_s2);
    lv_obj_set_width(ui_nextButton, 50);
    lv_obj_set_height(ui_nextButton, 40);
    lv_obj_set_x(ui_nextButton, 70);
    lv_obj_set_y(ui_nextButton, 40);
    lv_obj_set_align(ui_nextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nextLabel = lv_label_create(ui_nextButton);
    lv_obj_set_width(ui_nextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nextLabel, "");

    ui_playButton = lv_btn_create(ui_s2);
    lv_obj_set_width(ui_playButton, 40);
    lv_obj_set_height(ui_playButton, 40);
    lv_obj_set_x(ui_playButton, 0);
    lv_obj_set_y(ui_playButton, 40);
    lv_obj_set_align(ui_playButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playLabel = lv_label_create(ui_playButton);
    lv_obj_set_width(ui_playLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playLabel, "");

    ui_volumeSlider = lv_slider_create(ui_s2);
    lv_slider_set_range(ui_volumeSlider, 0, 21);
    lv_slider_set_value(ui_volumeSlider, 12, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volumeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volumeSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_volumeSlider, 14);
    lv_obj_set_height(ui_volumeSlider, 111);
    lv_obj_set_x(ui_volumeSlider, 133);
    lv_obj_set_y(ui_volumeSlider, 38);
    lv_obj_set_align(ui_volumeSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_volumeSlider, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label25 = lv_label_create(ui_s2);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -51);
    lv_obj_set_y(ui_Label25, -70);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "0n-70s.mp3");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_s2);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 131);
    lv_obj_set_y(ui_Label26, -35);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "音量");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_misc, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicDropdown = lv_dropdown_create(ui_s2);
    lv_dropdown_set_options(ui_musicDropdown, "");
    lv_obj_set_width(ui_musicDropdown, 122);
    lv_obj_set_height(ui_musicDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_musicDropdown, 86);
    lv_obj_set_y(ui_musicDropdown, -70);
    lv_obj_set_align(ui_musicDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musicDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label27 = lv_label_create(ui_s2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, -105);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "音乐电台");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speakButton = lv_btn_create(ui_speechScreen);
    lv_obj_set_width(ui_speakButton, 56);
    lv_obj_set_height(ui_speakButton, 30);
    lv_obj_set_x(ui_speakButton, 116);
    lv_obj_set_y(ui_speakButton, -90);
    lv_obj_set_align(ui_speakButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speakButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_speakButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_speakButton);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "录音");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_tipFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speakButton, ui_event_speakButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speechScreen, ui_event_speechScreen, LV_EVENT_ALL, NULL);

}
