// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_lampButton_lampButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_lampButton = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lampButtonCB(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lampButtonCB(e);
    }
}

// COMPONENT lampButton

lv_obj_t * ui_lampButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_lampButton;
    cui_lampButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_lampButton, 80);
    lv_obj_set_height(cui_lampButton, 80);
    lv_obj_set_x(cui_lampButton, 50);
    lv_obj_set_y(cui_lampButton, -40);
    lv_obj_set_align(cui_lampButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_lampButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_lampButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_lampButton, lv_color_hex(0x415062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_lampButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_lampButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_lampButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(cui_lampButton, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(cui_lampButton, 150, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(cui_lampButton, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(cui_lampButton, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(cui_lampButton, lv_color_hex(0x728BFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(cui_lampButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(cui_lampButton, lv_color_hex(0xA94949), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(cui_lampButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_stateLabel2;
    cui_stateLabel2 = lv_label_create(cui_lampButton);
    lv_obj_set_width(cui_stateLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_stateLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_stateLabel2, 17);
    lv_obj_set_y(cui_stateLabel2, 21);
    lv_obj_set_align(cui_stateLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_stateLabel2, "OFF");
    lv_obj_set_style_text_color(cui_stateLabel2, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_stateLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_stateLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_stateImage2;
    cui_stateImage2 = lv_img_create(cui_lampButton);
    lv_img_set_src(cui_stateImage2, &ui_img_l1_png);
    lv_obj_set_width(cui_stateImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_stateImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_stateImage2, -15);
    lv_obj_set_y(cui_stateImage2, -16);
    lv_obj_set_align(cui_stateImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_stateImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_stateImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_stateImage2, 120);

    lv_obj_t * cui_nameLabel2;
    cui_nameLabel2 = lv_label_create(cui_lampButton);
    lv_obj_set_width(cui_nameLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_nameLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_nameLabel2, -19);
    lv_obj_set_y(cui_nameLabel2, 22);
    lv_obj_set_align(cui_nameLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_nameLabel2, "灯1");
    lv_obj_set_style_text_color(cui_nameLabel2, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_nameLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_nameLabel2, &ui_font_unit, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LAMPBUTTON_NUM);
    children[UI_COMP_LAMPBUTTON_LAMPBUTTON] = cui_lampButton;
    children[UI_COMP_LAMPBUTTON_STATELABEL2] = cui_stateLabel2;
    children[UI_COMP_LAMPBUTTON_STATEIMAGE2] = cui_stateImage2;
    children[UI_COMP_LAMPBUTTON_NAMELABEL2] = cui_nameLabel2;
    lv_obj_add_event_cb(cui_lampButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_lampButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_lampButton, ui_event_comp_lampButton_lampButton, LV_EVENT_ALL, children);
    ui_comp_lampButton_create_hook(cui_lampButton);
    return cui_lampButton;
}

