// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_StartupScreen
void ui_StartupScreen_screen_init(void);
void ui_event_StartupScreen(lv_event_t * e);
lv_obj_t * ui_StartupScreen;
lv_obj_t * ui_Image5;
lv_obj_t * ui_tipLabel;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_Label7;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label2;
void ui_event_timeLabel(lv_event_t * e);
lv_obj_t * ui_timeLabel;
lv_obj_t * ui_weathericonImage;
lv_obj_t * ui_weathericonImage2;
lv_obj_t * ui_weathericonImage3;
lv_obj_t * ui_weathericonImage4;
lv_obj_t * ui_weatherLabel;
lv_obj_t * ui_Container1;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label8;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label11;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label6;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_cityLabel;
lv_obj_t * ui_statusbarLabel;


// SCREEN: ui_DateScreen
void ui_DateScreen_screen_init(void);
void ui_event_DateScreen(lv_event_t * e);
lv_obj_t * ui_DateScreen;
lv_obj_t * ui_TemperatureWifget;
lv_obj_t * ui_TemperatureLabel;
lv_obj_t * ui_Label3;
void ui_event_TemperatureArc(lv_event_t * e);
lv_obj_t * ui_TemperatureArc;
lv_obj_t * ui_HumidityWifget;
lv_obj_t * ui_HumidityLabel;
lv_obj_t * ui_Label4;
void ui_event_HumidityArc(lv_event_t * e);
lv_obj_t * ui_HumidityArc;
lv_obj_t * ui_MQ2Wifget;
lv_obj_t * ui_MQLabel;
lv_obj_t * ui_Label9;
void ui_event_MQArc(lv_event_t * e);
lv_obj_t * ui_MQArc;
void ui_event_Panel3(lv_event_t * e);
lv_obj_t * ui_Panel3;


// SCREEN: ui_lampScreen
void ui_lampScreen_screen_init(void);
void ui_event_lampScreen(lv_event_t * e);
lv_obj_t * ui_lampScreen;
void ui_event_TabView2(lv_event_t * e);
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPage1;
void ui_event_lampButton3(lv_event_t * e);
lv_obj_t * ui_lampButton3;
lv_obj_t * ui_stateLabel1;
lv_obj_t * ui_stateImage1;
lv_obj_t * ui_nameLabel1;
lv_obj_t * ui_TabPage2;
void ui_event_Panel10(lv_event_t * e);
lv_obj_t * ui_Panel10;


// SCREEN: ui_Calendar
void ui_Calendar_screen_init(void);
void ui_event_Calendar(lv_event_t * e);
lv_obj_t * ui_Calendar;
void ui_event_Calendar2(lv_event_t * e);
lv_obj_t * ui_Calendar2;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;


// SCREEN: ui_setchooseScreen
void ui_setchooseScreen_screen_init(void);
void ui_event_setchooseScreen(lv_event_t * e);
lv_obj_t * ui_setchooseScreen;
void ui_event_Panel6(lv_event_t * e);
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Container2;
void ui_event_speechSetButton(lv_event_t * e);
lv_obj_t * ui_speechSetButton;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Image12;
void ui_event_timeSetButton(lv_event_t * e);
lv_obj_t * ui_timeSetButton;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Image11;
void ui_event_networkSetButton(lv_event_t * e);
lv_obj_t * ui_networkSetButton;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Image10;
void ui_event_wifiSetButton(lv_event_t * e);
lv_obj_t * ui_wifiSetButton;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Panel9;
void ui_event_monitorSetButton(lv_event_t * e);
lv_obj_t * ui_monitorSetButton;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Image13;


// SCREEN: ui_set1Screen
void ui_set1Screen_screen_init(void);
void ui_event_set1Screen(lv_event_t * e);
lv_obj_t * ui_set1Screen;
void ui_event_Panel5(lv_event_t * e);
lv_obj_t * ui_Panel5;
lv_obj_t * ui_chooseTabView;
lv_obj_t * ui_w1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_wifiSwitch;
lv_obj_t * ui_wifiStateLabel;
lv_obj_t * ui_wifilistPanel;
lv_obj_t * ui_ipLabel;
lv_obj_t * ui_w2;
lv_obj_t * ui_Label16;
lv_obj_t * ui_mqttStateLabel;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label17;
void ui_event_mqttuseButton(lv_event_t * e);
lv_obj_t * ui_mqttuseButton;
lv_obj_t * ui_mqttConnectStateLabel;
lv_obj_t * ui_w3;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label10;
void ui_event_timeuseButton(lv_event_t * e);
lv_obj_t * ui_timeuseButton;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label31;
void ui_event_themeSwitch(lv_event_t * e);
lv_obj_t * ui_themeSwitch;
lv_obj_t * ui_Label36;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_W4;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label32;
lv_obj_t * ui_speechDropdown;
lv_obj_t * ui_Label33;
lv_obj_t * ui_aimodeDropdown;
lv_obj_t * ui_W5;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label67;
void ui_event_cameraButton(lv_event_t * e);
lv_obj_t * ui_cameraButton;
lv_obj_t * ui_cameraipLabel;
lv_obj_t * ui_Label35;


// SCREEN: ui_speechScreen
void ui_speechScreen_screen_init(void);
void ui_event_speechScreen(lv_event_t * e);
lv_obj_t * ui_speechScreen;
void ui_event_Panel8(lv_event_t * e);
lv_obj_t * ui_Panel8;
lv_obj_t * ui_TabView4;
lv_obj_t * ui_s1;
void ui_event_speakButton(lv_event_t * e);
lv_obj_t * ui_speakButton;
lv_obj_t * ui_speakLabel;
lv_obj_t * ui_speechStateLabel;
lv_obj_t * ui_expressionChart;
lv_obj_t * ui_s2;
lv_obj_t * ui_prevButton;
lv_obj_t * ui_prevLabel;
lv_obj_t * ui_nextButton;
lv_obj_t * ui_nextLabel;
lv_obj_t * ui_playButton;
lv_obj_t * ui_playLabel;
lv_obj_t * ui_volumeSlider;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_musicDropdown;
lv_obj_t * ui_Label27;


// SCREEN: ui_monitorScreen
void ui_monitorScreen_screen_init(void);
void ui_event_monitorScreen(lv_event_t * e);
lv_obj_t * ui_monitorScreen;
void ui_event_Panel4(lv_event_t * e);
lv_obj_t * ui_Panel4;
void ui_event_connectCameraButton(lv_event_t * e);
lv_obj_t * ui_connectCameraButton;
lv_obj_t * ui_cameraLabel;
lv_obj_t * ui_cameraStateLabel;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_a[1] = {&ui_img_a1_png};
const lv_img_dsc_t * ui_imgset_c[1] = {&ui_img_c1_png};
const lv_img_dsc_t * ui_imgset_cc[1] = {&ui_img_cc1_png};
const lv_img_dsc_t * ui_imgset_l[2] = {&ui_img_l1_png, &ui_img_l2_png};
const lv_img_dsc_t * ui_imgset_s[1] = {&ui_img_s1_png};
const lv_img_dsc_t * ui_imgset_t[1] = {&ui_img_t2_png};
const lv_img_dsc_t * ui_imgset_vv[1] = {&ui_img_vv1_png};
const lv_img_dsc_t * ui_imgset_w[1] = {&ui_img_w1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_StartupScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_timeLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Calendar_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setchooseScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_setchooseScreen_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_lampScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_lampScreen_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        monitorScreenOCD(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DateScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_DateScreen_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speakScreenCD(e);
    }
}
void ui_event_DateScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_TemperatureArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_TemperatureLabel, target, "", "°C");
    }
}
void ui_event_HumidityArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_HumidityLabel, target, "", "%");
    }
}
void ui_event_MQArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_TemperatureLabel, target, "", "°C");
    }
}
void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_lampScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_TabView2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_lampButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_stateImage1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_l2_png);
        _ui_label_set_property(ui_stateLabel1, _UI_LABEL_PROPERTY_TEXT, "ON");
        lampButtonCB(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_stateImage1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_l1_png);
        _ui_label_set_property(ui_stateLabel1, _UI_LABEL_PROPERTY_TEXT, "OFF");
        lampButtonCB(e);
    }
}
void ui_event_Panel10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Calendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Calendar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_setchooseScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_speechSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setChooseScreenCD(e);
    }
}
void ui_event_timeSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setChooseScreenCD(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_networkSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setChooseScreenCD(e);
    }
}
void ui_event_wifiSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setChooseScreenCD(e);
    }
}
void ui_event_monitorSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setChooseScreenCD(e);
    }
}
void ui_event_set1Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        chooseScreenFCD(e);
    }
}
void ui_event_Panel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_mqttuseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chooseBtEventCD(e);
        _ui_checked_set_text_value(ui_mqttConnectStateLabel, target, "解绑", "绑定");
    }
}
void ui_event_timeuseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chooseBtEventCD(e);
    }
}
void ui_event_themeSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchThemesCD(e);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        controlBrightnessCD(e);
    }
}
void ui_event_cameraButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chooseBtEventCD(e);
    }
}
void ui_event_speechScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        speakScreenFCD(e);
    }
}
void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_speakButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        speakScreenCD(e);
    }
}
void ui_event_monitorScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        monitorScreenFCD(e);
    }
}
void ui_event_Panel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_connectCameraButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        cameraScreenCD(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        cameraScreenCD(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_StartupScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_DateScreen_screen_init();
    ui_lampScreen_screen_init();
    ui_Calendar_screen_init();
    ui_setchooseScreen_screen_init();
    ui_set1Screen_screen_init();
    ui_speechScreen_screen_init();
    ui_monitorScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_StartupScreen);
}
