// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_StartupScreen
void ui_StartupScreen_screen_init(void);
void ui_event_StartupScreen(lv_event_t * e);
extern lv_obj_t * ui_StartupScreen;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_tipLabel;
extern lv_obj_t * ui_Spinner2;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
void ui_event_timeLabel(lv_event_t * e);
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_weathericonImage;
extern lv_obj_t * ui_weathericonImage2;
extern lv_obj_t * ui_weathericonImage3;
extern lv_obj_t * ui_weathericonImage4;
extern lv_obj_t * ui_weatherLabel;
extern lv_obj_t * ui_Container1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label8;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label11;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label6;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_cityLabel;
extern lv_obj_t * ui_statusbarLabel;
// SCREEN: ui_DateScreen
void ui_DateScreen_screen_init(void);
void ui_event_DateScreen(lv_event_t * e);
extern lv_obj_t * ui_DateScreen;
extern lv_obj_t * ui_TemperatureWifget;
extern lv_obj_t * ui_TemperatureLabel;
extern lv_obj_t * ui_Label3;
void ui_event_TemperatureArc(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc;
extern lv_obj_t * ui_HumidityWifget;
extern lv_obj_t * ui_HumidityLabel;
extern lv_obj_t * ui_Label4;
void ui_event_HumidityArc(lv_event_t * e);
extern lv_obj_t * ui_HumidityArc;
extern lv_obj_t * ui_MQ2Wifget;
extern lv_obj_t * ui_MQLabel;
extern lv_obj_t * ui_Label9;
void ui_event_MQArc(lv_event_t * e);
extern lv_obj_t * ui_MQArc;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
// SCREEN: ui_lampScreen
void ui_lampScreen_screen_init(void);
void ui_event_lampScreen(lv_event_t * e);
extern lv_obj_t * ui_lampScreen;
void ui_event_TabView2(lv_event_t * e);
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_lampButton1;
extern lv_obj_t * ui_lampButton2;
extern lv_obj_t * ui_lampButton3;
extern lv_obj_t * ui_lampButton4;
extern lv_obj_t * ui_TabPage2;
void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
// SCREEN: ui_Calendar
void ui_Calendar_screen_init(void);
void ui_event_Calendar(lv_event_t * e);
extern lv_obj_t * ui_Calendar;
void ui_event_Calendar2(lv_event_t * e);
extern lv_obj_t * ui_Calendar2;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
// SCREEN: ui_setchooseScreen
void ui_setchooseScreen_screen_init(void);
void ui_event_setchooseScreen(lv_event_t * e);
extern lv_obj_t * ui_setchooseScreen;
void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Container2;
void ui_event_speechSetButton(lv_event_t * e);
extern lv_obj_t * ui_speechSetButton;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Image12;
void ui_event_timeSetButton(lv_event_t * e);
extern lv_obj_t * ui_timeSetButton;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image11;
void ui_event_networkSetButton(lv_event_t * e);
extern lv_obj_t * ui_networkSetButton;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image10;
void ui_event_wifiSetButton(lv_event_t * e);
extern lv_obj_t * ui_wifiSetButton;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Panel9;
void ui_event_monitorSetButton(lv_event_t * e);
extern lv_obj_t * ui_monitorSetButton;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Image13;
// SCREEN: ui_set1Screen
void ui_set1Screen_screen_init(void);
void ui_event_set1Screen(lv_event_t * e);
extern lv_obj_t * ui_set1Screen;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_chooseTabView;
extern lv_obj_t * ui_w1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_wifiSwitch;
extern lv_obj_t * ui_wifiStateLabel;
extern lv_obj_t * ui_wifilistPanel;
extern lv_obj_t * ui_ipLabel;
extern lv_obj_t * ui_w2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_mqttSwitch;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
void ui_event_mqttuseButton(lv_event_t * e);
extern lv_obj_t * ui_mqttuseButton;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_mqttStateLabel;
extern lv_obj_t * ui_w3;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
void ui_event_timeuseButton(lv_event_t * e);
extern lv_obj_t * ui_timeuseButton;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_W4;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_speechDropdown;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_aimodeDropdown;
extern lv_obj_t * ui_W5;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label67;
void ui_event_cameraButton(lv_event_t * e);
extern lv_obj_t * ui_cameraButton;
extern lv_obj_t * ui_cameraipLabel;
extern lv_obj_t * ui_Label35;
// SCREEN: ui_speechScreen
void ui_speechScreen_screen_init(void);
void ui_event_speechScreen(lv_event_t * e);
extern lv_obj_t * ui_speechScreen;
void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_TabView4;
extern lv_obj_t * ui_s1;
void ui_event_speakButton(lv_event_t * e);
extern lv_obj_t * ui_speakButton;
extern lv_obj_t * ui_speakLabel;
extern lv_obj_t * ui_speechStateLabel;
extern lv_obj_t * ui_expressionChart;
extern lv_obj_t * ui_s2;
extern lv_obj_t * ui_prevButton;
extern lv_obj_t * ui_prevLabel;
extern lv_obj_t * ui_nextButton;
extern lv_obj_t * ui_nextLabel;
extern lv_obj_t * ui_playButton;
extern lv_obj_t * ui_playLabel;
extern lv_obj_t * ui_volumeSlider;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_musicDropdown;
extern lv_obj_t * ui_Label27;
// SCREEN: ui_monitorScreen
void ui_monitorScreen_screen_init(void);
void ui_event_monitorScreen(lv_event_t * e);
extern lv_obj_t * ui_monitorScreen;
void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
void ui_event_connectCameraButton(lv_event_t * e);
extern lv_obj_t * ui_connectCameraButton;
extern lv_obj_t * ui_cameraLabel;
extern lv_obj_t * ui_cameraStateLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_icon_png);    // assets/icon.png
LV_IMG_DECLARE(ui_img_31831977);    // assets/5@1x.png
LV_IMG_DECLARE(ui_img_1282432712);    // assets/0@1x.png
LV_IMG_DECLARE(ui_img_520433372);    // assets/4@1x.png
LV_IMG_DECLARE(ui_img_1809401540);    // assets/13@1x.png
LV_IMG_DECLARE(ui_img_configure_png);    // assets/configure.png
LV_IMG_DECLARE(ui_img_lamps_png);    // assets/lamps.png
LV_IMG_DECLARE(ui_img_s1_png);    // assets/s1.png
LV_IMG_DECLARE(ui_img_data_png);    // assets/data.png
LV_IMG_DECLARE(ui_img_y1_png);    // assets/y1.png
LV_IMG_DECLARE(ui_img_l2_png);    // assets/l2.png
LV_IMG_DECLARE(ui_img_l1_png);    // assets/l1.png
LV_IMG_DECLARE(ui_img_a1_png);    // assets/a1.png
LV_IMG_DECLARE(ui_img_t2_png);    // assets/t2.png
LV_IMG_DECLARE(ui_img_w1_png);    // assets/w1.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_c1_png);    // assets/c1.png



LV_FONT_DECLARE(ui_font_dan);
LV_FONT_DECLARE(ui_font_misc);
LV_FONT_DECLARE(ui_font_smartsystem);
LV_FONT_DECLARE(ui_font_tipFont);
LV_FONT_DECLARE(ui_font_unit);
LV_FONT_DECLARE(ui_font_UniversalFont);
LV_FONT_DECLARE(ui_font_weatherfont);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
