// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACK 0
#define UI_THEME_COLOR_FONT 1
#define UI_THEME_COLOR_BTN 2
#define UI_THEME_COLOR_BOEDER 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_DARKTHEME 1

#define UI_THEME_LIGHTTHEME 2

extern const ui_theme_variable_t _ui_theme_color_back[3];
extern const ui_theme_variable_t _ui_theme_alpha_back[3];

extern const ui_theme_variable_t _ui_theme_color_font[3];
extern const ui_theme_variable_t _ui_theme_alpha_font[3];

extern const ui_theme_variable_t _ui_theme_color_btn[3];
extern const ui_theme_variable_t _ui_theme_alpha_btn[3];

extern const ui_theme_variable_t _ui_theme_color_boeder[3];
extern const ui_theme_variable_t _ui_theme_alpha_boeder[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
