// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_back[3] = {0x1F2228, 0x101820, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_back[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_font[3] = {0xFFFFFF, 0xFFFFFF, 0x090808};
const ui_theme_variable_t _ui_theme_alpha_font[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_btn[3] = {0x415062, 0x415062, 0xA9B2B5};
const ui_theme_variable_t _ui_theme_alpha_btn[3] = {255, 255, 200};

const ui_theme_variable_t _ui_theme_color_boeder[3] = {0x8D78F4, 0x101820, 0xE6E2E6};
const ui_theme_variable_t _ui_theme_alpha_boeder[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DARKTHEME;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

